const badges = {
  react: "https://img.shields.io/badge/React-61DAFB?style=for-the-badge&logo=React&logoColor=black",
  redux: "https://img.shields.io/badge/Redux-764ABC?style=for-the-badge&logo=Redux&logoColor=white",
  axios: "https://img.shields.io/badge/Axios-5A29E4?style=for-the-badge&logo=Axios&logoColor=white",
  vercel: "https://img.shields.io/badge/Vercel-000000?style=for-the-badge&logo=Vercel&logoColor=white",
  kakaoApi: "https://img.shields.io/badge/Kakao Api-FFCD00?style=for-the-badge&logo=Kakao&logoColor=black",
  styledComponents: "https://img.shields.io/badge/styled components-DB7093?style=for-the-badge&logo=styled-components&logoColor=white",
  swiper: "https://img.shields.io/badge/Swiper-6332F6?style=for-the-badge&logo=Swiper&logoColor=white",
  lodash: "https://img.shields.io/badge/Lodash-3492FF?style=for-the-badge&logo=Lodash&logoColor=white",
  stomp: "https://img.shields.io/badge/Stomp-353535?style=for-the-badge&logoColor=white",
  reactRouter: "https://img.shields.io/badge/React Router-CA4245?style=for-the-badge&logo=React Router&logoColor=white",
};

export const data = [
  {
    id: 0,
    title: "댕과사전",
    descript: "견주들을 위한 커뮤니티",
    stack: [
      badges.react,
      badges.redux,
      badges.axios,
      badges.vercel,
      badges.kakaoApi,
      badges.styledComponents,
      badges.swiper,
      badges.lodash,
      badges.stomp,
      badges.reactRouter,
    ],
    projUrl: "https://daengtionary.site/",
    github: "https://github.com/daengtionary/Frontend",
    thumbnail: "https://user-images.githubusercontent.com/90291796/194318131-e9b56e93-30bc-4714-a68a-2863372fe655.jpg",
  },
  {
    id: 1,
    title: "제목",
    descript: "설명",
    stack: [badges.react],
    projUrl: "URL",
    github: "깃헙",
    thumbnail: "썸넬",
  },
  {
    id: 2,
    title: "제목",
    descript: "설명",
    stack: [badges.react],
    projUrl: "URL",
    github: "깃헙",
    thumbnail: "썸넬",
  },
  {
    id: 3,
    title: "제목",
    descript: "설명",
    stack: [badges.react],
    projUrl: "URL",
    github: "깃헙",
    thumbnail: "썸넬",
  },
];
